<a href="https://colab.research.google.com/github/git-fahad/demo-repo/blob/main/numpy_demo_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

ar = np.array([1, 2, 3])

print(ar)

[1 2 3]


In [4]:
## 2D array

ar_2 = np.array([(1, 2, 4), (5, 3, 2)])
print(ar_2)

[[1 2 4]
 [5 3 2]]


In [5]:
## Confirming that numpy consumes less memory
import numpy as np
import sys
import time

S = range(1000)
D = np.arange(1000)

## Both variables contain 1000 integer values - from 0 to 1000

##Calculating the size

print(sys.getsizeof(5) * len(S))

print(D.size*D.itemsize)

28000
8000


In [1]:
## Comparing the time taken to add two lists & np arrays

import numpy as np
import sys
import time

size = 1000000

L1 = range(size)
L2 = range(size)

A1 = np.arange(size)
A2 = np.arange(size)

start = time.time()

result = [(x,y) for x, y in zip (L1, L2)]

print((time.time() - start) * 1000)
#print(result)

result = A1 + A2

print((time.time() - start) * 1000)
#print(result)

373.57115745544434
434.71455574035645


Numpy arrays take more time to add than lists, however, numpy calculation is easier

In [9]:
y = np.array([(1,2,3),(4,5,6)])
print(np.size(y))
print(np.shape(y))
print(y)

6
(2, 3)
[[1 2 3]
 [4 5 6]]


In [13]:
y = np.array([(1,2,3,5,7),(4,5,6,7,9)])
y = np.reshape(14,1)
print(y)

[14]


In [40]:
## Operations

y = np.array([(1,2,3,5,7),(4,5,6,7,9)])

print(y)

print(y[1, 3])

print(np.max(y[0]))

print(np.min(y))

print(np.sum(y[0]))

print('\n')
print(y.sum(axis=1))

#sqroot
print(np.sqrt(y))

print('\n')
#stddeviation
print(np.std(y))

print('\n')
print(np.mean(y))

[[1 2 3 5 7]
 [4 5 6 7 9]]
7
7
1
18


[18 31]
[[1.         1.41421356 1.73205081 2.23606798 2.64575131]
 [2.         2.23606798 2.44948974 2.64575131 3.        ]]


2.3430749027719964


4.9


In [48]:
##Mathematical operators are straight forward + - * /

## Stacking
# Vertical and Horizontal

a = np.array([(1,2,3,4), (5,4,3,2)])
b = np.array([(5,2,6,4), (7,4,8,2)])

print(a)
print(b)

#print(np.vstack(a,b))

[[1 2 3 4]
 [5 4 3 2]]
[[5 2 6 4]
 [7 4 8 2]]
